"""For assigned_tasks

Revision ID: 0a123a6155fd
Revises: e3c518c6b6c9
Create Date: 2024-12-21 11:41:05.161131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a123a6155fd'
down_revision: Union[str, None] = 'e3c518c6b6c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_tasks', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_foreign_key(None, 'assigned_tasks', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(None, 'assigned_tasks', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'assigned_tasks', 'status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assigned_tasks', type_='foreignkey')
    op.drop_constraint(None, 'assigned_tasks', type_='foreignkey')
    op.drop_constraint(None, 'assigned_tasks', type_='foreignkey')
    op.drop_column('assigned_tasks', 'id')
    # ### end Alembic commands ###
