"""Add UserType (for router)

Revision ID: e3c518c6b6c9
Revises: e63ef19571a6
Create Date: 2024-12-19 18:27:38.976646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c518c6b6c9'
down_revision: Union[str, None] = 'e63ef19571a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertypes', sa.Column('usertype', sa.String(), nullable=False))
    op.drop_column('usertypes', 'usertypes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertypes', sa.Column('usertypes', sa.VARCHAR(), nullable=False))
    op.drop_column('usertypes', 'usertype')
    # ### end Alembic commands ###
